### PR TITLE
Div in between comments bug

### PR DESCRIPTION
**Pull request by danpersa**

### CODE REVIEW

**Comment by danpersa** [comment]
this branch has merge conflicts... will you fix it? :)

**Comment by kaygorodov** [comment]
yep, I will look into it.

**Comment by kaygorodov** [comment]
Hi @danpersa ,

Please check https://github.com/zalando/beard/pull/44, if it is OK, you can accept changes into the div-in-between-comments-bug branch and then merge it into the master.

**Comment by danpersa** [comment]
:ok_hand:

**Comment by danpersa** [comment]
@kaygorodov you should also do a pull request https://github.com/danpersa/beard-book to change the comments style :)

**Pull request merged**
