### PR TITLE
Initial gh-pages commit

### PR DESCRIPTION
**Pull request by axyz**
Just a starting point :)

### CODE REVIEW

**Comment by danpersa** [comment]
Good starting point :)

**Comment by danpersa** [comment]
do you have a vectorial image you could upload?

**Comment by axyz** [comment]
yes I will add the svg

Il giorno lun 18 gen 2016 alle ore 18:13 danpersa notifications@github.com
ha scritto:

**Comment by danpersa** [comment]
Please add it to the pull request

**Comment by axyz** [comment]
done ;)

**Pull request merged**
